name: 'TghaAction'
author: 'Nurzhan Aitbayev'
description: 'TghaAction'
branding:
  icon: book-open
  color: green
inputs:
  token:
    description: 'Token'
    required: true
    default: '.'
  chat-id:
    description: 'Chat Id'
    required: true
    default: '-1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.chat-id }}
  entrypoint: "/entrypoint.sh"